# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'etrimain.ui'
#
# Created: Sat Sep 18 20:55:34 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EtriMainWindow(object):
    def setupUi(self, EtriMainWindow):
        EtriMainWindow.setObjectName("EtriMainWindow")
        EtriMainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(EtriMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.right_layout = QtGui.QVBoxLayout()
        self.right_layout.setObjectName("right_layout")
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.right_layout.addItem(spacerItem)
        self.group_input = QtGui.QGroupBox(self.centralwidget)
        self.group_input.setObjectName("group_input")
        self.gridLayout_9 = QtGui.QGridLayout(self.group_input)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.combo_layer = QtGui.QComboBox(self.group_input)
        self.combo_layer.setObjectName("combo_layer")
        self.gridLayout_9.addWidget(self.combo_layer, 0, 0, 1, 1)
        self.Bloadlayer = QtGui.QPushButton(self.group_input)
        self.Bloadlayer.setObjectName("Bloadlayer")
        self.gridLayout_9.addWidget(self.Bloadlayer, 0, 1, 1, 1)
        self.right_layout.addWidget(self.group_input)
        self.group_profiles = QtGui.QGroupBox(self.centralwidget)
        self.group_profiles.setObjectName("group_profiles")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.group_profiles)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Badd_profile = QtGui.QCommandLinkButton(self.group_profiles)
        self.Badd_profile.setObjectName("Badd_profile")
        self.verticalLayout_2.addWidget(self.Badd_profile)
        self.Bdel_profile = QtGui.QCommandLinkButton(self.group_profiles)
        self.Bdel_profile.setObjectName("Bdel_profile")
        self.verticalLayout_2.addWidget(self.Bdel_profile)
        self.right_layout.addWidget(self.group_profiles)
        self.group_thresholds = QtGui.QGroupBox(self.centralwidget)
        self.group_thresholds.setMaximumSize(QtCore.QSize(388, 16777215))
        self.group_thresholds.setObjectName("group_thresholds")
        self.formLayout = QtGui.QFormLayout(self.group_thresholds)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.cbox_samethresholds = QtGui.QCheckBox(self.group_thresholds)
        self.cbox_samethresholds.setObjectName("cbox_samethresholds")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.cbox_samethresholds)
        self.cbox_noveto = QtGui.QCheckBox(self.group_thresholds)
        self.cbox_noveto.setObjectName("cbox_noveto")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.cbox_noveto)
        self.cbox_sameqp = QtGui.QCheckBox(self.group_thresholds)
        self.cbox_sameqp.setObjectName("cbox_sameqp")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.cbox_sameqp)
        self.right_layout.addWidget(self.group_thresholds)
        self.group_affectation = QtGui.QGroupBox(self.centralwidget)
        self.group_affectation.setObjectName("group_affectation")
        self.gridLayout_8 = QtGui.QGridLayout(self.group_affectation)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.cutlevel_layout = QtGui.QHBoxLayout()
        self.cutlevel_layout.setObjectName("cutlevel_layout")
        self.label_cutlevel = QtGui.QLabel(self.group_affectation)
        self.label_cutlevel.setObjectName("label_cutlevel")
        self.cutlevel_layout.addWidget(self.label_cutlevel)
        self.spinbox_cutlevel = QtGui.QDoubleSpinBox(self.group_affectation)
        self.spinbox_cutlevel.setMinimum(0.5)
        self.spinbox_cutlevel.setMaximum(1.0)
        self.spinbox_cutlevel.setSingleStep(0.01)
        self.spinbox_cutlevel.setProperty("value", 0.75)
        self.spinbox_cutlevel.setObjectName("spinbox_cutlevel")
        self.cutlevel_layout.addWidget(self.spinbox_cutlevel)
        self.gridLayout_8.addLayout(self.cutlevel_layout, 0, 0, 1, 1)
        self.procedure_layout = QtGui.QHBoxLayout()
        self.procedure_layout.setObjectName("procedure_layout")
        self.label_procedure = QtGui.QLabel(self.group_affectation)
        self.label_procedure.setObjectName("label_procedure")
        self.procedure_layout.addWidget(self.label_procedure)
        self.combo_procedure = QtGui.QComboBox(self.group_affectation)
        self.combo_procedure.setObjectName("combo_procedure")
        self.combo_procedure.addItem("")
        self.combo_procedure.addItem("")
        self.procedure_layout.addWidget(self.combo_procedure)
        self.gridLayout_8.addLayout(self.procedure_layout, 1, 0, 1, 1)
        self.right_layout.addWidget(self.group_affectation)
        self.Bgenerate = QtGui.QCommandLinkButton(self.centralwidget)
        self.Bgenerate.setObjectName("Bgenerate")
        self.right_layout.addWidget(self.Bgenerate)
        self.gridLayout.addLayout(self.right_layout, 0, 1, 1, 1)
        self.Tab_params = QtGui.QTabWidget(self.centralwidget)
        self.Tab_params.setObjectName("Tab_params")
        self.tab_criterions = QtGui.QWidget()
        self.tab_criterions.setObjectName("tab_criterions")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_criterions)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table_crit = QtGui.QTableWidget(self.tab_criterions)
        self.table_crit.setDragEnabled(False)
        self.table_crit.setAlternatingRowColors(False)
        self.table_crit.setShowGrid(False)
        self.table_crit.setCornerButtonEnabled(False)
        self.table_crit.setRowCount(0)
        self.table_crit.setObjectName("table_crit")
        self.table_crit.setColumnCount(3)
        self.table_crit.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_crit.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_crit.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_crit.setHorizontalHeaderItem(2, item)
        self.table_crit.horizontalHeader().setVisible(True)
        self.table_crit.horizontalHeader().setDefaultSectionSize(100)
        self.table_crit.horizontalHeader().setHighlightSections(False)
        self.table_crit.verticalHeader().setVisible(False)
        self.table_crit.verticalHeader().setHighlightSections(False)
        self.table_crit.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_2.addWidget(self.table_crit, 0, 0, 1, 1)
        self.Tab_params.addTab(self.tab_criterions, "")
        self.tab_profiles = QtGui.QWidget()
        self.tab_profiles.setObjectName("tab_profiles")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_profiles)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.table_prof = QtGui.QTableWidget(self.tab_profiles)
        self.table_prof.setObjectName("table_prof")
        self.table_prof.setColumnCount(0)
        self.table_prof.setRowCount(0)
        self.gridLayout_5.addWidget(self.table_prof, 0, 0, 1, 1)
        self.tab_thresholds = QtGui.QTabWidget(self.tab_profiles)
        self.tab_thresholds.setTabPosition(QtGui.QTabWidget.North)
        self.tab_thresholds.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_thresholds.setObjectName("tab_thresholds")
        self.tab_indiff = QtGui.QWidget()
        self.tab_indiff.setObjectName("tab_indiff")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_indiff)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_indiff = QtGui.QTableWidget(self.tab_indiff)
        self.table_indiff.setObjectName("table_indiff")
        self.table_indiff.setColumnCount(0)
        self.table_indiff.setRowCount(0)
        self.gridLayout_3.addWidget(self.table_indiff, 0, 1, 1, 1)
        self.tab_thresholds.addTab(self.tab_indiff, "")
        self.tab_pref = QtGui.QWidget()
        self.tab_pref.setObjectName("tab_pref")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_pref)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.table_pref = QtGui.QTableWidget(self.tab_pref)
        self.table_pref.setObjectName("table_pref")
        self.table_pref.setColumnCount(0)
        self.table_pref.setRowCount(0)
        self.gridLayout_4.addWidget(self.table_pref, 0, 0, 1, 1)
        self.tab_thresholds.addTab(self.tab_pref, "")
        self.tab_veto = QtGui.QWidget()
        self.tab_veto.setObjectName("tab_veto")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_veto)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.table_veto = QtGui.QTableWidget(self.tab_veto)
        self.table_veto.setObjectName("table_veto")
        self.table_veto.setColumnCount(0)
        self.table_veto.setRowCount(0)
        self.gridLayout_7.addWidget(self.table_veto, 0, 0, 1, 1)
        self.tab_thresholds.addTab(self.tab_veto, "")
        self.gridLayout_5.addWidget(self.tab_thresholds, 1, 0, 1, 1)
        self.Tab_params.addTab(self.tab_profiles, "")
        self.gridLayout.addWidget(self.Tab_params, 0, 0, 1, 1)
        EtriMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(EtriMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        EtriMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(EtriMainWindow)
        self.statusbar.setObjectName("statusbar")
        EtriMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EtriMainWindow)
        self.Tab_params.setCurrentIndex(0)
        self.tab_thresholds.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EtriMainWindow)

    def retranslateUi(self, EtriMainWindow):
        EtriMainWindow.setWindowTitle(QtGui.QApplication.translate("EtriMainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.group_input.setTitle(QtGui.QApplication.translate("EtriMainWindow", "Input Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.Bloadlayer.setText(QtGui.QApplication.translate("EtriMainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.group_profiles.setTitle(QtGui.QApplication.translate("EtriMainWindow", "Profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.Badd_profile.setText(QtGui.QApplication.translate("EtriMainWindow", "Add Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.Bdel_profile.setText(QtGui.QApplication.translate("EtriMainWindow", "Del Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.group_thresholds.setTitle(QtGui.QApplication.translate("EtriMainWindow", "Thresholds", None, QtGui.QApplication.UnicodeUTF8))
        self.cbox_samethresholds.setText(QtGui.QApplication.translate("EtriMainWindow", "Use same for all profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.cbox_noveto.setText(QtGui.QApplication.translate("EtriMainWindow", "No Veto", None, QtGui.QApplication.UnicodeUTF8))
        self.cbox_sameqp.setText(QtGui.QApplication.translate("EtriMainWindow", "Indifference = Preference", None, QtGui.QApplication.UnicodeUTF8))
        self.group_affectation.setTitle(QtGui.QApplication.translate("EtriMainWindow", "Affectation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cutlevel.setText(QtGui.QApplication.translate("EtriMainWindow", "Cutting level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_procedure.setText(QtGui.QApplication.translate("EtriMainWindow", "Procedure:", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_procedure.setItemText(0, QtGui.QApplication.translate("EtriMainWindow", "Pessimist", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_procedure.setItemText(1, QtGui.QApplication.translate("EtriMainWindow", "Optimist", None, QtGui.QApplication.UnicodeUTF8))
        self.Bgenerate.setText(QtGui.QApplication.translate("EtriMainWindow", "Generate Decision Map", None, QtGui.QApplication.UnicodeUTF8))
        self.table_crit.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("EtriMainWindow", "Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.table_crit.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("EtriMainWindow", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab_params.setTabText(self.Tab_params.indexOf(self.tab_criterions), QtGui.QApplication.translate("EtriMainWindow", "Criterions", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_thresholds.setTabText(self.tab_thresholds.indexOf(self.tab_indiff), QtGui.QApplication.translate("EtriMainWindow", "Indifference", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_thresholds.setTabText(self.tab_thresholds.indexOf(self.tab_pref), QtGui.QApplication.translate("EtriMainWindow", "Preference", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_thresholds.setTabText(self.tab_thresholds.indexOf(self.tab_veto), QtGui.QApplication.translate("EtriMainWindow", "Veto", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab_params.setTabText(self.Tab_params.indexOf(self.tab_profiles), QtGui.QApplication.translate("EtriMainWindow", "Profiles", None, QtGui.QApplication.UnicodeUTF8))

